# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 73448a8e7953d1ed94561371a87fd49169a4c63f1853933cfb375eb4e53a8e2f78054bc40e957f16daac7479634ed37429215dd95a00d88e014ef313b31c83d3

test:
  secret_key_base: c42dff835edc3fab9342a2c35cce2d46838753ff444ebdce9f33718090354212e8158e3f0babfb23aa5e08294dd1e9663b3ee313c2081a77af657b90c089cc4e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
